version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: myappdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devuser"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: ./teste-back
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/myappdb
      SPRING_DATASOURCE_USERNAME: devuser
      SPRING_DATASOURCE_PASSWORD: devpassword
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./teste-front
    ports:
      - "5000:5000"
    depends_on:
      - backend

volumes:
  postgres_data:

