version: '3'
services:
  front:
    container_name: teste-front
    build: ./teste-front
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    networks:
      - front
    depends_on:
      - back

  back:
    container_name: teste-back
    build: ./teste-back
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydatabase
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - front
      - db
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - db

networks:
  front:
    driver: bridge
  db:
    driver: bridge

volumes:
  postgres-data: