name: Docker Compose Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build and Deploy with Docker Compose
        run: |
          docker-compose up --build -d
          sleep 10  # Wait for services to fully start
          docker-compose ps  # List running containers after startup
          curl http://localhost:8080  # Example: Test connectivity to service
          curl http://localhost:5000  # Example: Test connectivity to frontend service

      - name: Capture Docker Compose Logs
        run: |
          docker-compose logs > compose_logs.txt
        continue-on-error: true
        timeout-minutes: 5

      - name: Upload Logs as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: compose-logs
          path: compose_logs.txt
